# facebook auth config
from getenv import env

FACEBOOK_APP_ID = env("FACEBOOK_APP_ID")
FACEBOOK_API_KEY = env("FACEBOOK_API_KEY")
FACEBOOK_API_SECRET = env("FACEBOOK_API_SECRET")
FACEBOOK_REDIRECT_URI = env("FACEBOOK_REDIRECT_URI")
